# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'minitest'
gem 'guard'
gem 'guard-minitest'
gem 'wdm', '>= 0.1.0' if Gem.win_platform? # avoid polling for changes
